FROM node:alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install

FROM node:alpine as backend
ARG PORT=3000
ENV PORT=$PORT
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT npm start backend

FROM node:alpine AS frontend
ARG PORT=3333
ENV PORT=$PORT
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT npm start frontend -- --port=$PORT --host=0.0.0.0